FissionAndFusion/FnFnCoreWallet

- CMakeLists.txt
- network/mvproto.cpp
- src/entry.cpp
- src/rpcmod.cpp
- walleve/walleve/console/console.cpp
- walleve/walleve/netio/ioclient.cpp
ssl 1.1.0 not source compatible with ssl 1.0.x (api changed)
> [#]: fix compatible with boost 1.67.0,ssl 1.1.0

- src/dispatcher.cpp
- src/event.h
- src/mvbase.h
- src/mvtype.h
- src/service.cpp
- src/service.h
以下功能：
Service模块notification接口开发，为SocketApi模块提供block/tx更新事件
已经完成，请求合并到主分支。
> task #16  

- .gitignore
- INSTALL.sh
- src/CMakeLists.txt
- src/config.cpp
- src/config.h
- src/entry.cpp
- src/entry.h
- src/mode/basic_config.cpp
- src/mode/basic_config.h
- src/mode/config_type.h
- src/mode/mint_config.cpp
- src/mode/mint_config.h
- src/mode/mode.h
- src/mode/mode_impl.h
- src/mode/mode_type.h
- src/mode/module_type.h
- src/mode/network_config.cpp
- src/mode/network_config.h
- src/mode/rpc_config.cpp
- src/mode/rpc_config.h
- src/mode/storage_config.cpp
- src/mode/storage_config.h
- src/multiverse.cpp
- src/rpcmod.h
- src/service.cpp
- walleve/walleve/docker/config.cpp
- walleve/walleve/docker/config.h
- walleve/walleve/util.h
- Create src/mode dictionary. It contains *Mode*(server, console, miner etc.), *Module*(txpool, httpserver etc. common inheritance from IWalleveBase), *Config*(CMvNetworkConfig, CMvRPCConfig), and their relationship.
- Based on first, in **entry.cpp**, Initialization is modular.
> task#34 pr.

- .gitignore
- INSTALL.sh
- src/CMakeLists.txt
- src/config.cpp
- src/config.h
- src/entry.cpp
- src/entry.h
- src/mode/basic_config.cpp
- src/mode/basic_config.h
- src/mode/config_type.h
- src/mode/mint_config.cpp
- src/mode/mint_config.h
- src/mode/mode.h
- src/mode/mode_impl.h
- src/mode/mode_type.h
- src/mode/module_type.h
- src/mode/network_config.cpp
- src/mode/network_config.h
- src/mode/rpc_config.cpp
- src/mode/rpc_config.h
- src/mode/storage_config.cpp
- src/mode/storage_config.h
- src/multiverse.cpp
- src/rpcmod.h
- src/service.cpp
- walleve/walleve/docker/config.cpp
- walleve/walleve/docker/config.h
- walleve/walleve/util.h
Reverts FissionAndFusion/FnFnCoreWallet#28
> Revert "Revert "task#34 pr.""

- src/schedule.cpp
Fixed bug reported by [cppcheck](http://cppcheck.net/) static analysis tool
> [#]: Fixed bug in CSchedule::RemoveOrphan

- storage/blockdb.cpp
- storage/txpooldb.cpp
- storage/walletdb.cpp
MySQL create table default engine=InnoDB
Signed-off-by: Zhang WenChao <zhangwenchao001@gmail.com>
> Edit: MySQL create table default engine=InnoDB

- crypto/key.cpp
- crypto/key.h
- network/mvpeernet.h
- script/template/rpc.json
- src/consensus.h
- src/dbpserver.cpp
- src/netchn.h
- src/network.h
- src/rpc/rpc_type.h
- src/rpcclient.h
- src/rpcmod.cpp
- src/service.h
- src/txpool.h
- src/wallet.cpp
- src/wallet.h
- src/worldline.h
- walleve/walleve/http/httpget.h
Except comment of commits, also modified type of `nVersion` in class `CKey` from **int** to **uint32**.   
Because there is exact 4 bytes when `Save()` and `Load()`.
> Sht task#20

- INSTALL.sh
- script/rpc_generator.py
- script/rpc_protocol_generator.py
- script/template/options.json
- script/template/rpc.json
- src/CMakeLists.txt
- src/entry.cpp
- src/rpc/rpc.cpp
- src/rpc/rpc_error.cpp
- src/rpc/rpc_error.h
- src/rpc/rpc_req.cpp
- src/rpc/rpc_resp.cpp
- src/rpcclient.cpp
- src/rpcmod.cpp
- src/rpcmod.h
- src/version.h
- test/CMakeLists.txt
- test/uint256_tests.cpp
- test/version_tests.cpp
CMakeLists:
1. Add 'make install' command to copy executable files to system path.
Functions:
1. Multiverse command 'multiverse -version'
2. RPC command 'multiverse-cli version'
3. Check RPC command version: if the MAJOR VERSION is not consistent, return a error code: -14
3. Create version_tests
> Add version function

- src/dbp-proto/lws.proto
- src/dbpserver.cpp
- src/dbpservice.cpp
- src/dbpservice.h
- src/dbptype.h
- src/dispatcher.cpp
- src/event.h
- src/mvtype.h
- src/service.cpp
The Description of [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=86&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> [+]: Add Change field for lws transaction on push tx

- script/template/options.json
- src/dbpclient.cpp
- src/dbpclient.h
- src/entry.cpp
Add private key configuration for forknode
> [+]: Add privatekey config for fornode

- src/dbp-proto/sn.proto
- src/dbpclient.cpp
- src/dbpclient.h
- src/dbpserver.cpp
- src/dbpservice.cpp
- src/dbpservice.h
- src/dbptype.h
- src/dbputils.h
Implemented sys-cmd block-cmd tx-cmd topic.
> Supernode all subscribe

- src/dbpservice.cpp
- src/dbpservice.h
- src/forkpeerevent.h
- src/forkpseudopeernet.cpp
- src/forkpseudopeernet.h
-  I Changed some snippet of codes for virtual peer net. please check it again if it is wrong.    @ouyun
- Port dbp service with virtual peer net
> [+]: Add support of virtual peernet in dbpservice

- src/netchn.cpp
- src/netchn.h
Cause changed some code in net channel, please wait @xdwangchn  reviewed complete and merge into supernode branch  ?
> [+]: Add fork filter in net channel

- src/forkpseudopeernet.cpp
1, bypass fork node to handle updateforkstate event
2, add invoking to netchannel for subscribing a fork
> pseudo peer net update

- script/template/rpc.json
- src/rpcmod.cpp
Signed-off-by: Zhang WenChao <zhangwenchao001@gmail.com>
> RPC list key change content #task id 104

- CMakeLists.txt
vim or emacs lint and auto complete
see: https://clang.llvm.org/docs/JSONCompilationDatabase.html
Signed-off-by: Zhang WenChao <zhangwenchao001@gmail.com>
> CMake export compile commands

- script/template/rpc.json
- src/rpcmod.cpp
1）修改了看板新提的三个BUG；
2）修改了人工测试新增加的BUG；
> Rpc bug mod

- CMakeLists.txt
Check OpenSSL Version is 1.1.x
> [#] CMakeLists: Check OpenSSL Version

- src/worldline.cpp
Fix [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=184&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> Getlastblocktime bug

- network/mvpeernet.cpp
- script/template/options.json
- src/network.cpp
- walleve/walleve/peernet/peernet.h
Completed [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=195&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> Task195 ip port config

- network/mvpeernet.cpp
- walleve/walleve/peernet/peernet.cpp
- walleve/walleve/peernet/peernet.h
Completed [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=135&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> [#] PeerNet: Add Remove Peer(4) IP filter

- src/entry.cpp
- src/event.h
- src/mvtype.h
- src/rpcmod.cpp
- src/rpcmod.h
- walleve/walleve/docker/docker.cpp
- walleve/walleve/event/eventproc.cpp
- walleve/walleve/event/eventproc.h
- walleve/walleve/netio/netio.h
1. Add a multi-thread module CRPCModWorker.
2. CRPCMod receives message from CHttpServer. Then decompose the message into uint works and post them to CRPCModWorker(support batch standard of JSON-RPC 2.0)
> Multithreading CRPCMod

- walleve/walleve/peernet/peernet.cpp
- walleve/walleve/peernet/peernet.h
Completed [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=61&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> [#] PeerNet: RemovePeer to close connection when RemoveNode called

- common/template/catagory.h
- common/template/fork.cpp
- common/template/fork.h
- common/template/template.cpp
- common/template/template.h
- src/core.cpp
- src/forkmanager.cpp
- src/wallet.cpp
1. Completed redeeming function of fork template.
2. Adjust RPC getbalance result field - "locked" that adds the coins of locked coin template
> Completed fork template redeeming function

- network/mvpeernet.cpp
- network/mvpeernet.h
- walleve/walleve/peernet/epmngr.cpp
- walleve/walleve/peernet/epmngr.h
- walleve/walleve/peernet/nodemngr.h
- walleve/walleve/peernet/peernet.cpp
- walleve/walleve/peernet/peernet.h
Completed [Task](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=120&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
**Test method:**
Node A configured IP:port gateway and start node A, then , Use Node B connect to Node A to receive a bunch of blocks generated from Node A, In this way, Node A's score on Node B increases with the number of blocks received. Finally, Use Node C connect to Node B, Node C will receive Good Node Address(configured in Node A's config file)
> Peernet addr distribute policy

- test/ipv6_tests.cpp
Add unit test about [Task129](https://dev.fnfn.app/?controller=TaskViewController&action=readonly&task_id=129&token=2b0b9205d79a27b22fd34a971c63479f13a8b2b43428fa6fc2bd6e0f93df)
> Resolve multi ip
